name: DevOps
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  ci:
    name: Test - Unit & Integration & SonarCloudSacan
    runs-on: ubuntu-latest # maos-latest macos-11 windows-2019 ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-modes
      - name: Sonar
        if: success() # always() failure() succes()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=LuisLoboR16_iwvg-devops-lobo-luis
          -Dsonar.organization=luislobor16
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}